### ISSUE TITLE
client alias

### ISSUE THREAD

**Issue by coricidin12** [oznu/unifi-events#1]
Great module, thanks! Is there any way to get events with the client aliases instead of the MAC address or hostname? Or some way to retrieve the MAC > alias index?

**Comment by oznu** [comment]
There are a few undocumented methods that I use in my projects to get this information. I just [added another](https://github.com/oznu/unifi-events/commit/8f0d0853b095e422ccb55409b144855b8b8a169f) to make it easier to retrieve the details for a single client via MAC address.

```js
const UnifiEvents = require('unifi-events')

const unifi = new UnifiEvents({
  controller: 'https://demo.ubnt.com',
  username: 'superadmin',
  password: 'password'
})

unifi.on('event', (data) => {

  // mac address is `.user` for regular networks and `.guest` for guest networks
  unifi.getClient(data.user || data.guest).then((client) => {
    console.log(client)

    // the client alias is in available on the `client.name` property
    console.log(client.name)
  })

})
```

Other available methods:

```js

// Return a list of all connected WiFi clients
unifi.getClients().then((data) => {
  console.log(data)
})

// Return a list of all UniFi sites
unifi.getSites().then((data) => {
  console.log(data)
})
```

**Comment by coricidin12** [comment]
That works great, thanks!
