### ISSUE TITLE
Port to Axios since request is deprecated

### ISSUE THREAD

**Issue by worldwidewoogie** [oznu/unifi-events#15]
This isn't an issue so much as an FYI. I was starting a new project and didn't want to base it on request, since it's deprecated, but I really liked unifi-events. So I essentially ported it to Axios:

https://github.com/worldwidewoogie/unifi-axios-events

Thanks a lot for the code!

**Comment by oznu** [comment]
Thanks, I've been meaning to do this at some point. Feel free to post a PR with the changes.

**Comment by worldwidewoogie** [comment]
I've posted a PR. Thanks!
